apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  labels:
    app: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      enableServiceLinks: false
      containers:
        - name: webgoat
          image: {IMAGE}
          imagePullPolicy: IfNotPresent
          env:
            # - name: SERVER_PORT
            #   value: "8080"
            - name: WEBGOAT_PORT
              value: "8080"
            - name: WEBWOLF_PORT
              value: "9090"
            - name: TZ
              value: Europe/Paris
          ports:
            - containerPort: 8080
              name: webgoat
            - containerPort: 9090
              name: webwolf
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /WebGoat
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /WebGoat
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat
  labels:
    app: webgoat
spec:
  selector:
    app: webgoat
  ports:
    - name: webgoat
      port: 8081
      targetPort: 8080
    - name: webwolf
      port: 9091
      targetPort: 9090
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat
  # annotations:
    # appgw.ingress.kubernetes.io/backend-path-prefix: /
  labels:
    app: webgoat
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /WebGoat
            pathType: Prefix
            backend:
              service:
                name: webgoat
                port:
                  number: 8081
          - path: /WebWolf
            pathType: Prefix
            backend:
              service:
                name: webgoat
                port:
                  number: 9091
